"""cria tabelas do banco

Revision ID: e4ca02a53bb1
Revises: 
Create Date: 2026-06-02 13:15:52.698107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ca02a53bb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsaveis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siape', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cargo', sa.Enum('PROFESSOR', 'PSICOLOGO', 'AGENTE', 'COORDENADOR', name='cargo', native_enum=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statususuario', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('siape')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('curso', sa.String(), nullable=False),
    sa.Column('ano', sa.String(), nullable=False),
    sa.Column('necessidade_especial', sa.String(), nullable=False),
    sa.Column('cid', sa.String(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusaluno', native_enum=False), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_solicitacao', sa.Date(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusdocumentacao', native_enum=False), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Enum('PRIMEIRO', 'SEGUNDO', name='semestre', native_enum=False), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_turmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('materia', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='statusprofessorturma', native_enum=False), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reunioes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'REALIZADA', 'PENDENTE', name='statusreuniao', native_enum=False), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_solicitacao', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('CONCLUIDO', 'PENDENTE', name='statussolicitacao', native_enum=False), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes')
    op.drop_table('reunioes')
    op.drop_table('professor_turmas')
    op.drop_table('ocorrencias')
    op.drop_table('turmas')
    op.drop_table('documentacoes')
    op.drop_table('atendimentos')
    op.drop_table('alunos')
    op.drop_table('usuarios')
    op.drop_table('responsaveis')
    # ### end Alembic commands ###
